package middleware

import (
	"net/http"

	"github.com/radiantgarden/weave-adapters/internal/core/apierror"
	"github.com/radiantgarden/weave-adapters/internal/core/events/catalog"
)

// ProblemErrors rewrites the router's own 404 and 405 responses as problem+json.
//
// 03-api-conventions requires every error to share one shape, "including
// 401/404 from middleware" — but the two most common errors a client meets are
// generated by http.ServeMux, which answers with plain text ("404 page not
// found\n") and no request ID. A generic client would then have to special-case
// exactly the responses it hits most.
//
// This runs innermost, wrapping the mux, and is deliberately one place rather
// than a handler registered per route: the mux produces these responses itself,
// so no route-level code can intercept them.
func ProblemErrors(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		next.ServeHTTP(&problemWriter{ResponseWriter: w, request: r}, r)
	})
}

// problemWriter replaces a router-generated 404/405 with problem+json.
//
// The decision is made at WriteHeader, before any body byte reaches the client,
// so nothing is buffered and no other response is delayed — a streaming handler
// passes through untouched.
type problemWriter struct {
	http.ResponseWriter

	request *http.Request
	// replaced records that this response was rewritten, so the router's
	// plain-text body is dropped rather than appended to the JSON.
	replaced bool
	// wrote records that the status is committed, so a second WriteHeader
	// (which net/http would warn about) is ignored.
	wrote bool
}

func (w *problemWriter) WriteHeader(code int) {
	if w.wrote {
		return
	}

	w.wrote = true

	if !w.shouldReplace(code) {
		w.ResponseWriter.WriteHeader(code)

		return
	}

	w.replaced = true

	// Write onto the wrapped writer, not this one, or WriteHeader would recurse.
	// The Allow header the mux already set survives: WriteError only replaces
	// Content-Type and the body.
	apierror.WriteError(w.ResponseWriter, w.request, w.problemFor(code))
}

func (w *problemWriter) Write(b []byte) (int, error) {
	if w.replaced {
		// The router's "404 page not found" would otherwise land after the JSON
		// body. Report success: the bytes were handled, just not forwarded.
		return len(b), nil
	}

	if !w.wrote {
		w.wrote = true
	}

	return w.ResponseWriter.Write(b)
}

// Unwrap keeps optional ResponseWriter capabilities reachable through
// http.ResponseController.
func (w *problemWriter) Unwrap() http.ResponseWriter {
	return w.ResponseWriter
}

// shouldReplace reports whether this response is a router-generated error.
//
// A problem+json content type means the response came from apierror — a handler
// or the auth middleware already rendered it — so it is left alone. That check
// is what keeps this from double-handling our own 404s.
func (w *problemWriter) shouldReplace(code int) bool {
	if code != http.StatusNotFound && code != http.StatusMethodNotAllowed {
		return false
	}

	return w.Header().Get("Content-Type") != apierror.ContentType
}

// problemFor builds the error for a router-generated status.
func (w *problemWriter) problemFor(code int) error {
	if code == http.StatusMethodNotAllowed {
		return apierror.New(catalog.API902,
			"method", w.request.Method,
			"allow", w.Header().Get("Allow"),
		)
	}

	return apierror.NotFound("route " + w.request.Method + " " + w.request.URL.Path)
}
