// Package common provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package common

// Defines values for ProblemType.
const (
	WeaveAdaptersBackendError       ProblemType = "weave-adapters:backend-error"
	WeaveAdaptersBackendTimeout     ProblemType = "weave-adapters:backend-timeout"
	WeaveAdaptersBackendUnavailable ProblemType = "weave-adapters:backend-unavailable"
	WeaveAdaptersInternal           ProblemType = "weave-adapters:internal"
	WeaveAdaptersMethodNotAllowed   ProblemType = "weave-adapters:method-not-allowed"
	WeaveAdaptersNotFound           ProblemType = "weave-adapters:not-found"
	WeaveAdaptersUnauthorized       ProblemType = "weave-adapters:unauthorized"
	WeaveAdaptersValidationFailed   ProblemType = "weave-adapters:validation-failed"
)

// Valid indicates whether the value is a known member of the ProblemType enum.
func (e ProblemType) Valid() bool {
	switch e {
	case WeaveAdaptersBackendError:
		return true
	case WeaveAdaptersBackendTimeout:
		return true
	case WeaveAdaptersBackendUnavailable:
		return true
	case WeaveAdaptersInternal:
		return true
	case WeaveAdaptersMethodNotAllowed:
		return true
	case WeaveAdaptersNotFound:
		return true
	case WeaveAdaptersUnauthorized:
		return true
	case WeaveAdaptersValidationFailed:
		return true
	default:
		return false
	}
}

// FieldError One field-level validation failure.
type FieldError struct {
	// Field The parameter or body field that was rejected.
	//
	// Example: pageSize
	Field string `json:"field"`

	// Message What was expected of that field. Client-safe by construction — it describes the expectation, never internal state.
	//
	// Example: must be at least 1
	Message string `json:"message"`
}

// Problem An RFC 9457 problem detail. Returned with Content-Type application/problem+json for every client-facing error, including the 401 and 404/405 produced by middleware rather than by a handler.
type Problem struct {
	// BackendError A sanitized message from the backend service, present only when the failure originated there. Adapters are responsible for stripping credentials and internal hostnames before setting it.
	//
	// Example: DHCP server rejected the scope: subnet already in use
	BackendError string `json:"backendError,omitempty"`

	// Detail Explains this specific occurrence. Curated for clients — it is rendered from the backing event's ResponseDetail and never carries an internal error message.
	//
	// Example: The requested lease 10.0.0.5 was not found.
	Detail string `json:"detail,omitempty"`

	// Errors Every field that failed validation. All failures are reported at once so a client fixes them in one round trip rather than discovering them one attempt at a time.
	Errors []FieldError `json:"errors,omitempty"`

	// Instance The request path the error occurred on.
	//
	// Example: /api/v1/leases/10.0.0.5
	Instance string `json:"instance,omitempty"`

	// RequestId Correlates this response with the adapter's logs; the same value is returned in the X-Request-Id header.
	//
	// Example: 9f1c2d3e4a5b6c7d
	RequestId string `json:"requestId,omitempty"`

	// Status The HTTP status code, repeated in the body per RFC 9457.
	//
	// Example: 404
	Status int `json:"status"`

	// Title Short, human-readable summary of the error class.
	//
	// Example: Not found
	Title string `json:"title"`

	// Type Stable slug identifying the error class. Clients may switch on it; it is the one field guaranteed not to change wording.
	// The enum lists the codes core defines. An adapter may add its own, so a client must treat an unrecognised value as an error it does not specifically handle rather than as a protocol violation.
	//
	// Example: weave-adapters:not-found
	Type ProblemType `json:"type"`
}

// ProblemType The problem types this version of core defines. An adapter may add its own, but never a second error shape.
// Entries exist only for codes something actually returns. The backend codes are live: an adapter maps its backend”'s failures onto them, so a client sees backend-unavailable or backend-error with a 502 and backend-timeout with a 504 rather than one indistinguishable 500. The rest of the taxonomy in 02-shared-core.md (conflict, precondition-failed) still arrives with the code that emits it.
type ProblemType string
