// Package common provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package common

import (
	"time"
)

// Defines values for JobStatus.
const (
	Failed    JobStatus = "failed"
	Pending   JobStatus = "pending"
	Running   JobStatus = "running"
	Succeeded JobStatus = "succeeded"
)

// Valid indicates whether the value is a known member of the JobStatus enum.
func (e JobStatus) Valid() bool {
	switch e {
	case Failed:
		return true
	case Pending:
		return true
	case Running:
		return true
	case Succeeded:
		return true
	default:
		return false
	}
}

// Job An asynchronous operation, pollable with ETag support so a client watching a long mutation pays for a 304 rather than a body per poll.
type Job struct {
	// CompletedAt When the job reached a terminal state. Absent while it is still pending or running.
	//
	// Example: 2026-07-18T09:02:41Z
	CompletedAt *time.Time `json:"completedAt,omitempty"`

	// CreatedAt When the job was accepted, RFC 3339 UTC.
	//
	// Example: 2026-07-18T09:02:36Z
	CreatedAt time.Time `json:"createdAt"`

	// Error Why the job failed, present only in the failed state. The same problem+json a synchronous failure would have returned, so a client has one error shape either way.
	Error *Problem `json:"error,omitempty"`

	// Id Identifier, unique within the adapter. Also the trailing segment of the Location header that created the job.
	//
	// Example: 01J9Z6X2QK7N4V8TA3B5C6D7E8
	Id string `json:"id"`

	// Operation What the job is doing, for an operator reading a job list. Free-form and adapter-defined; clients must not switch on it.
	//
	// Example: createScope
	Operation string `json:"operation,omitempty"`

	// Resource Relative link to the resource the job acts on, once one exists. On a successful create this is where the new resource lives.
	//
	// Example: /api/v1/scopes/10.0.0.0
	Resource string `json:"resource,omitempty"`

	// Status Job lifecycle. Only pending and running are non-terminal; a client stops polling on anything else. Finer-grained progress belongs in the operator's event log, not in this contract.
	//
	// Example: running
	Status JobStatus `json:"status"`
}

// JobStatus Job lifecycle. Only pending and running are non-terminal; a client stops polling on anything else. Finer-grained progress belongs in the operator's event log, not in this contract.
//
// Example: running
type JobStatus string
