// Package common provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package common

// PageEnvelope The collection envelope every list endpoint returns. Adapters define their own list schema with the same two fields and a concrete item type; this component fixes the field names and their optionality, which is what a generic client depends on.
type PageEnvelope struct {
	// Items The page's items. Always present and always an array — an empty collection is [], never null, because clients iterate it directly.
	Items []map[string]interface{} `json:"items"`

	// NextPageToken The cursor as an opaque token, echoed back as ?pageToken=. Absent on the last page; its presence — not a full page of items — is what tells a client to request the next one.
	//
	// Example: eyJ2IjoxLCJzIjoibGVhc2VzIiwiayI6ImJHVmhjMlV0TURBME1nIn0
	NextPageToken string `json:"nextPageToken,omitempty"`

	// NextPageUrl The same cursor as a ready-to-fetch link, for clients that follow links rather than echo tokens. Present exactly when nextPageToken is, and never instead of it.
	// Always a relative reference, so an adapter never has to derive its own external base URL from Host or X-Forwarded-* headers.
	// Carries every query parameter of the request that produced it, with only pageToken replaced — a link-following client sends nothing but this link, so a dropped filter would yield unfiltered later pages.
	//
	// Example: /api/v1/leases?pageSize=50&pageToken=eyJ2IjoxLCJzIjoibGVhc2VzIn0
	NextPageUrl string `json:"nextPageUrl,omitempty"`
}

// PageSize defines model for PageSize.
type PageSize = int

// PageToken defines model for PageToken.
type PageToken = string
