// Package dhcpwindows provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package dhcpwindows

import (
	externalRef0 "github.com/radiantgarden/weave-adapters/api/common"
)

// Defines values for AddressFamily.
const (
	Ipv4 AddressFamily = "ipv4"
)

// Valid indicates whether the value is a known member of the AddressFamily enum.
func (e AddressFamily) Valid() bool {
	switch e {
	case Ipv4:
		return true
	default:
		return false
	}
}

// Defines values for HealthStatus.
const (
	Healthy     HealthStatus = "healthy"
	Unavailable HealthStatus = "unavailable"
	Unhealthy   HealthStatus = "unhealthy"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case Healthy:
		return true
	case Unavailable:
		return true
	case Unhealthy:
		return true
	default:
		return false
	}
}

// Defines values for ScopeState.
const (
	Active   ScopeState = "Active"
	Inactive ScopeState = "Inactive"
)

// Valid indicates whether the value is a known member of the ScopeState enum.
func (e ScopeState) Valid() bool {
	switch e {
	case Active:
		return true
	case Inactive:
		return true
	default:
		return false
	}
}

// Defines values for ScopeType.
const (
	Bootp ScopeType = "Bootp"
	Both  ScopeType = "Both"
	Dhcp  ScopeType = "Dhcp"
)

// Valid indicates whether the value is a known member of the ScopeType enum.
func (e ScopeType) Valid() bool {
	switch e {
	case Bootp:
		return true
	case Both:
		return true
	case Dhcp:
		return true
	default:
		return false
	}
}

// AddressFamily Always `ipv4` for now. The field exists so IPv6 lands additively rather than as a breaking change: Windows models v6 scopes as a prefix rather than a start/end range, so folding both into one schema now would be a guess.
//
// Example: ipv4
type AddressFamily string

// HealthComponent defines model for HealthComponent.
type HealthComponent struct {
	// Detail Human-readable explanation, present when there is something to say beyond the status.
	//
	// Example: scope query failed: the DhcpServer module is not installed
	Detail string `json:"detail,omitempty"`

	// Fields Operator-useful detail about this component, as flat strings. The keys are diagnostic rather than contractual — a client must not switch on them.
	// For `dhcp-server`, note that `server` and `identity` are different things and are separately configured: `server` is the host the query was sent to (`(local host)` when unset, which is the default), while `identity` is the provisioned name every `wadaptId` derives from. A fleet of IDs that changed without any scope changing is explained by the second, never the first.
	//
	// Example: {"identity":"dhcp01.example.test","psEdition":"Desktop","psVersion":"5.1.20348.558","scopeCount":"3","server":"(local host)"}
	Fields map[string]string `json:"fields,omitempty"`

	// Name Stable identifier for the component. `core` is the adapter process; `dhcp-server` is the DHCP backend.
	//
	// Example: dhcp-server
	Name string `json:"name"`

	// Status Ordered healthy < unhealthy < unavailable; the overall status is the worst of the components. `unhealthy` means degraded but reachable and answers 200; only `unavailable` answers 503.
	//
	// Example: healthy
	Status HealthStatus `json:"status"`
}

// HealthResponse Deliberately shaped like weave's own daemon health response rather than like /healthz or /readyz, so weave's generic health client works against an adapter unchanged.
type HealthResponse struct {
	// Components One entry per checked component. Always present.
	Components []HealthComponent `json:"components"`

	// Status The worst status across all components. Read the HTTP status code for a routing decision; read this for what to tell an operator.
	Status HealthStatus `json:"status"`

	// UptimeSeconds Seconds since the process started — measured from process start, not from the moment the listener bound.
	//
	// Example: 86400
	UptimeSeconds int64 `json:"uptimeSeconds"`

	// Version The adapter version, stamped at build time.
	//
	// Example: 1.4.0
	Version string `json:"version"`
}

// HealthStatus Ordered healthy < unhealthy < unavailable; the overall status is the worst of the components. `unhealthy` means degraded but reachable and answers 200; only `unavailable` answers 503.
//
// Example: healthy
type HealthStatus string

// Scope One Windows DHCP scope.
// The field set is deliberately narrower than the cmdlet's. NapEnable and NapProfile are omitted because Network Access Protection was removed from Windows Server in 2016 and surfacing a dead technology would put it in this contract permanently; the Cim* and PSComputerName properties are transport metadata rather than scope data; and ActivatePolicies, Delay and MaxBootpClients have no consumer yet.
type Scope struct {
	// AddressFamily Always `ipv4` for now. The field exists so IPv6 lands additively rather than as a breaking change: Windows models v6 scopes as a prefix rather than a start/end range, so folding both into one schema now would be a guess.
	//
	// Example: ipv4
	AddressFamily AddressFamily `json:"addressFamily"`

	// Description Free-text description. Omitted when the server holds none — the convention is that absent fields are omitted rather than nulled.
	//
	// Example: created by hand
	Description string `json:"description,omitempty"`

	// EndRange Last address the scope may lease.
	//
	// Example: 192.168.178.210
	EndRange string `json:"endRange"`

	// LeaseDurationSeconds Lease duration in whole seconds. Windows carries a TimeSpan; the convention across every adapter is integer seconds with the unit in the field name.
	//
	// Example: 691200
	LeaseDurationSeconds int `json:"leaseDurationSeconds"`

	// Name The scope's administrative name.
	//
	// Example: manual_test_01
	Name string `json:"name"`

	// ScopeId The scope's subnet address — Windows' own key, and immutable. Unique per server but not across a fleet, which is why it is a filter here rather than the identity.
	//
	// Example: 192.168.178.0
	ScopeId string `json:"scopeId"`

	// StartRange First address the scope may lease.
	//
	// Example: 192.168.178.10
	StartRange string `json:"startRange"`

	// State Whether the scope is currently leasing addresses.
	//
	// Example: Active
	State ScopeState `json:"state"`

	// SubnetMask Example: 255.255.255.0
	SubnetMask string `json:"subnetMask"`

	// SuperscopeName The superscope this scope belongs to, omitted when it belongs to none. Read-only: reporting the name a scope already carries is not the same as modelling superscopes as a resource, which is deferred.
	//
	// Example: site-a
	SuperscopeName string `json:"superscopeName,omitempty"`

	// Type Which protocol the scope serves. Windows' own vocabulary, passed through unchanged.
	//
	// Example: Dhcp
	Type ScopeType `json:"type"`

	// WadaptId The scope's stable identity, and the key the item path will use.
	// Derived by the adapter, never stored on the DHCP server: base32hex(HMAC-SHA256(namespaceKey, serverName || 0x00 || scopeId)) truncated to 8 bytes, which always encodes to 13 characters in the RFC 4648 §7 extended-hex alphabet. Lowercase, unpadded, and never reformatted.
	// Stable for as long as the provisioned namespaceKey, the provisioned serverName and the scope's own subnet all hold still. Changing any of the three re-keys every scope it covers.
	//
	// Example: 8k2f5r9tc0hqm
	WadaptId string `json:"wadaptId"`
}

// ScopeCreate What a client supplies to create a scope. Deliberately narrower than Scope: it carries only what Windows accepts on `Add-DhcpServerv4Scope`, and nothing the server derives.
// Absent by design, and rejected if sent rather than ignored — silently dropping a field a client believed in is how two systems come to disagree about what was created:
//   - `scopeId` — Windows derives it as the network address of
//     `startRange` masked by `subnetMask`. A client that sent one could
//     disagree with the value the server is about to compute.
//   - `wadaptId` — derived from the provisioned server identity and the
//     subnet. Not a client's to choose.
//   - `addressFamily` — IPv4 is the only family this version serves, so the
//     field would be a constant a client could get wrong.
//   - `superscopeName` — assigning a scope to a superscope is a separate
//     operation on a resource this version does not model.
type ScopeCreate struct {
	// Description Free-text description. Omit rather than sending an empty string.
	//
	// Example: created by weave
	Description string `json:"description,omitempty"`

	// EndRange Last address the scope may lease. Must be at or after `startRange` and inside the same subnet.
	//
	// Example: 10.0.30.250
	EndRange string `json:"endRange"`

	// LeaseDurationSeconds Lease duration in whole seconds. Omitted, Windows applies its own default (8 days at the time of writing) — the adapter does not substitute one of its own, so the server's default remains the server's to change.
	//
	// Example: 691200
	LeaseDurationSeconds int `json:"leaseDurationSeconds,omitempty"`

	// Name Administrative name. Required by Windows, and the field an operator will actually recognise the scope by in the DHCP console.
	//
	// Example: lab-vlan-30
	Name string `json:"name"`

	// StartRange First address the scope may lease.
	//
	// Example: 10.0.30.10
	StartRange string `json:"startRange"`

	// State Whether the scope leases addresses immediately. Defaults to `Active` when omitted, matching the cmdlet.
	State ScopeState `json:"state,omitempty"`

	// SubnetMask The subnet mask. With `startRange` this determines the subnet, and therefore the scope's identity — two creates whose ranges fall in one subnet are the same scope and the second is a 409.
	//
	// Example: 255.255.255.0
	SubnetMask string `json:"subnetMask"`

	// Type Which protocol the scope serves. Defaults to `Dhcp` when omitted, matching the cmdlet.
	Type ScopeType `json:"type,omitempty"`
}

// ScopeList A page of scopes. Mirrors the shared PageEnvelope with a concrete item type, which is how every adapter's list schema is built: the envelope fixes the field names and their optionality, the adapter supplies the item.
type ScopeList struct {
	// Items The page's scopes. Always present and always an array — an empty collection is [], never null.
	Items []Scope `json:"items"`

	// NextPageToken The cursor as an opaque token, echoed back as ?pageToken=. Absent on the last page; its presence — not a full page of items — is what tells a client to request the next one.
	NextPageToken string `json:"nextPageToken,omitempty"`

	// NextPageUrl The same cursor as a ready-to-fetch link, for clients that follow links rather than echo tokens. Present exactly when nextPageToken is, and never instead of it.
	// Always relative, and carries every query parameter of the request that produced it with only pageToken replaced — a link-following client sends nothing but this link, so a dropped scopeId filter would widen every later page.
	//
	// Example: /api/v1/scopes?pageSize=50&pageToken=eyJ2IjoxLCJzIjoic2NvcGVzIn0
	NextPageUrl string `json:"nextPageUrl,omitempty"`
}

// ScopeState Whether the scope is currently leasing addresses.
//
// Example: Active
type ScopeState string

// ScopeType Which protocol the scope serves. Windows' own vocabulary, passed through unchanged.
//
// Example: Dhcp
type ScopeType string

// IfNoneMatch defines model for IfNoneMatch.
type IfNoneMatch = string

// ScopeIdFilter defines model for ScopeIdFilter.
type ScopeIdFilter = string

// WadaptIdPath defines model for WadaptIdPath.
type WadaptIdPath = string

// BackendFailed An RFC 9457 problem detail. Returned with Content-Type application/problem+json for every client-facing error, including the 401 and 404/405 produced by middleware rather than by a handler.
type BackendFailed = externalRef0.Problem

// BackendTimeout An RFC 9457 problem detail. Returned with Content-Type application/problem+json for every client-facing error, including the 401 and 404/405 produced by middleware rather than by a handler.
type BackendTimeout = externalRef0.Problem

// Conflict An RFC 9457 problem detail. Returned with Content-Type application/problem+json for every client-facing error, including the 401 and 404/405 produced by middleware rather than by a handler.
type Conflict = externalRef0.Problem

// Internal An RFC 9457 problem detail. Returned with Content-Type application/problem+json for every client-facing error, including the 401 and 404/405 produced by middleware rather than by a handler.
type Internal = externalRef0.Problem

// NotFound An RFC 9457 problem detail. Returned with Content-Type application/problem+json for every client-facing error, including the 401 and 404/405 produced by middleware rather than by a handler.
type NotFound = externalRef0.Problem

// PayloadTooLarge An RFC 9457 problem detail. Returned with Content-Type application/problem+json for every client-facing error, including the 401 and 404/405 produced by middleware rather than by a handler.
type PayloadTooLarge = externalRef0.Problem

// Unauthorized An RFC 9457 problem detail. Returned with Content-Type application/problem+json for every client-facing error, including the 401 and 404/405 produced by middleware rather than by a handler.
type Unauthorized = externalRef0.Problem

// UnsupportedMediaType An RFC 9457 problem detail. Returned with Content-Type application/problem+json for every client-facing error, including the 401 and 404/405 produced by middleware rather than by a handler.
type UnsupportedMediaType = externalRef0.Problem

// ValidationFailed An RFC 9457 problem detail. Returned with Content-Type application/problem+json for every client-facing error, including the 401 and 404/405 produced by middleware rather than by a handler.
type ValidationFailed = externalRef0.Problem

// ListScopesParams defines parameters for ListScopes.
type ListScopesParams struct {
	// PageSize Maximum items to return. Each endpoint documents its own default and maximum, so neither is fixed here.
	// A value above the endpoint's maximum is clamped to it rather than rejected, so a client must always treat nextPageToken — not the item count — as the authority on whether more items exist. A value that is not a positive integer is a 400.
	PageSize externalRef0.PageSize `form:"pageSize,omitempty" json:"pageSize,omitempty"`

	// PageToken Resumes a listing where the previous page ended. Opaque: clients must echo back a nextPageToken this endpoint returned and never construct or interpret one. A token that was not minted by this collection is a 400, never a silent restart from the first page.
	PageToken externalRef0.PageToken `form:"pageToken,omitempty" json:"pageToken,omitempty"`

	// ScopeId Returns only the scope with this subnet address. Exact equality — there is no filter DSL in v1.
	// `scopeId` is a filter and not the resource key. It is Windows' own identifier and unique per server, but private network addresses repeat across installations, so it does not identify a scope across a fleet. `wadaptId` does, and is what the item path will use.
	ScopeId ScopeIdFilter `form:"scopeId,omitempty" json:"scopeId,omitempty"`

	// IfNoneMatch An ETag this endpoint previously returned. Matching it yields 304 with no body.
	// Authentication runs outside the conditional wrapper, so a valid If-None-Match presented without credentials is a 401, never a 304.
	IfNoneMatch IfNoneMatch `json:"If-None-Match,omitempty"`
}

// GetScopeParams defines parameters for GetScope.
type GetScopeParams struct {
	// IfNoneMatch An ETag this endpoint previously returned. Matching it yields 304 with no body.
	// Authentication runs outside the conditional wrapper, so a valid If-None-Match presented without credentials is a 401, never a 304.
	IfNoneMatch IfNoneMatch `json:"If-None-Match,omitempty"`
}

// CreateScopeJSONRequestBody defines body for CreateScope for application/json ContentType.
type CreateScopeJSONRequestBody = ScopeCreate
