package config

import (
	"errors"
	"flag"
	"fmt"
	"slices"
	"strconv"
	"strings"
	"time"
	"unicode"

	"github.com/knadh/koanf/providers/confmap"
	"github.com/knadh/koanf/v2"
	"github.com/pelletier/go-toml/v2"
)

// commentWidth is where a rendered Usage comment wraps, chosen to match the
// width the hand-written config.example.toml already uses.
const commentWidth = 76

// renderHeader opens every generated file. It says what wrote the file and,
// more usefully, what is NOT in it — an operator who opens a four-line config
// and concludes the rest is unsupported has been misled by its brevity.
const renderHeader = `# Generated by weave-adapter-dhcp-windows.
#
# Only the values this host was provisioned with are written here. Every other
# key keeps its built-in default; see config.example.toml for the full set and
# what each one does.
#
# This file is the channel for identity.namespaceKey, which is backup-critical
# and cannot be recovered if lost. Back it up. ` + "`service secure`" + ` locks it down
# to SYSTEM and Administrators.
`

// Provisioned is one value to write into a generated config file.
//
// Secret and FreshlyGenerated say nothing to the renderer — the value is
// written either way — but they travel with the value because the caller that
// REPORTS on a provisioning run needs both, and deriving them a second time
// somewhere else is how a secret comes to be echoed.
type Provisioned struct {
	// Key is the registered, dotted config key.
	Key string
	// Value is the value to write, in the Go type the key's Type implies:
	// string, int, bool or time.Duration.
	Value any
	// Secret marks a value that must never be printed, logged or echoed back.
	Secret bool
	// FreshlyGenerated marks a value this run invented rather than was given,
	// which is what the "back this up" advice keys off.
	FreshlyGenerated bool
}

// Render produces a TOML config file carrying exactly the given values.
//
// Exactly those, and no others. Rendering the whole Spec would freeze today's
// defaults into every provisioned host: a file written with probeTimeout =
// "3s" keeps 3s after the default is raised, and it was raised — so the
// generated file would silently pin the value the measurement had just
// rejected. A key that is absent here resolves to whatever the binary defaults
// it to, which is the behaviour an operator gets by not mentioning it.
//
// Each value carries its key's Usage as a comment, so the file explains itself
// without a second copy of the documentation to keep in step.
//
// Strings are written as TOML literal strings wherever they can be, because
// almost every value setup writes is a Windows path and a literal string is
// the one form in which a backslash is not an escape. Getting that wrong is
// not a cosmetic failure: the file is written with the namespace key already
// in it, and a quoting mistake produces a config the loader rejects *after*
// the only copy of that key is on disk.
func Render(spec Spec, values []Provisioned) ([]byte, error) {
	index, err := spec.index()
	if err != nil {
		return nil, err
	}

	if err := checkProvisioned(index, values); err != nil {
		return nil, err
	}

	var b strings.Builder

	b.WriteString(renderHeader)

	// Bare keys before any table header: in TOML a key written after a [table]
	// belongs to that table, so a top-level key emitted late would silently
	// become identity.logFile and never be read.
	if err := renderGroup(&b, index, values, ""); err != nil {
		return nil, err
	}

	for _, table := range tablesOf(values) {
		b.WriteString("\n[" + table + "]\n")

		if err := renderGroup(&b, index, values, table); err != nil {
			return nil, err
		}
	}

	return []byte(b.String()), nil
}

// checkProvisioned reports every value that could not be written correctly.
//
// All of them at once, and before anything is rendered: the caller validates
// the rendered file and writes it only if that passes, so a partial render
// followed by a per-value failure would be the one shape that leaves a
// half-provisioned host.
func checkProvisioned(index map[string]Key, values []Provisioned) error {
	var errs []error

	seen := make(map[string]struct{}, len(values))

	for _, v := range values {
		key, registered := index[v.Key]
		if !registered {
			// Silence is the alternative: an unregistered key is written to
			// the file, parsed, and ignored by the loader, so the operator
			// gets a config that visibly says one thing and does another.
			errs = append(errs, fmt.Errorf("config: cannot render %q: it is not a registered key", v.Key))

			continue
		}

		if _, duplicate := seen[v.Key]; duplicate {
			errs = append(errs, fmt.Errorf("config: %q was provided twice", v.Key))

			continue
		}

		seen[v.Key] = struct{}{}

		if _, err := renderValue(key, v.Value); err != nil {
			errs = append(errs, err)
		}
	}

	return errors.Join(errs...)
}

// tablesOf returns the table names the values need, in first-seen order so the
// file's sections follow the order the caller provisioned them.
func tablesOf(values []Provisioned) []string {
	var out []string

	for _, v := range values {
		if table := tableOf(v.Key); table != "" && !slices.Contains(out, table) {
			out = append(out, table)
		}
	}

	return out
}

// tableOf returns the TOML table a dotted key belongs to, or "" for a bare
// top-level key.
func tableOf(key string) string {
	i := strings.LastIndex(key, ".")
	if i < 0 {
		return ""
	}

	return key[:i]
}

// leafOf returns the key's name within its table.
func leafOf(key string) string {
	return key[strings.LastIndex(key, ".")+1:]
}

// renderGroup writes every value belonging to one table, in the order given.
func renderGroup(b *strings.Builder, index map[string]Key, values []Provisioned, table string) error {
	for _, v := range values {
		if tableOf(v.Key) != table {
			continue
		}

		key := index[v.Key]

		literal, err := renderValue(key, v.Value)
		if err != nil {
			return err
		}

		b.WriteString(comment(key.Usage))
		b.WriteString(leafOf(v.Key) + " = " + literal + "\n")
	}

	return nil
}

// comment renders a key's Usage as wrapped TOML comment lines, with a blank
// line before it so the file reads as sections rather than a wall.
func comment(usage string) string {
	if usage == "" {
		return "\n"
	}

	var b strings.Builder

	b.WriteString("\n")

	line := "#"

	for word := range strings.FieldsSeq(usage) {
		if len(line)+1+len(word) > commentWidth && line != "#" {
			b.WriteString(line + "\n")
			line = "#"
		}

		line += " " + word
	}

	b.WriteString(line + "\n")

	return b.String()
}

// renderValue renders one value in the form its key's Type requires, refusing
// a value of the wrong Go type rather than stringifying it.
//
// Refusing matters more here than at load: a mis-typed value written into the
// file is not rejected until the next start, by which point the file — and the
// namespace key in it — is already on disk.
func renderValue(key Key, value any) (string, error) {
	switch key.Type {
	case TypeString:
		v, ok := value.(string)
		if !ok {
			return "", renderTypeError(key, value)
		}

		return tomlString(v), nil

	case TypeInt:
		v, ok := value.(int)
		if !ok {
			return "", renderTypeError(key, value)
		}

		return strconv.Itoa(v), nil

	case TypeBool:
		v, ok := value.(bool)
		if !ok {
			return "", renderTypeError(key, value)
		}

		return strconv.FormatBool(v), nil

	case TypeDuration:
		v, ok := value.(time.Duration)
		if !ok {
			return "", renderTypeError(key, value)
		}

		// As a string, because that is the only form the loader parses a
		// duration from in TOML.
		return tomlString(v.String()), nil

	default:
		return "", fmt.Errorf("config: cannot render %q: unknown type %d", key.Name, key.Type)
	}
}

// renderTypeError names the key, what arrived, and what the key needs.
func renderTypeError(key Key, value any) error {
	return fmt.Errorf("config: cannot render %q: it is a %s, got %T", key.Name, key.Type, value)
}

// tomlString renders a string as TOML.
//
// A literal string ('…') wherever possible, because nearly every value written
// here is a Windows path and a literal string is the one form in which a
// backslash is not an escape — C:\temp\new as a basic string would carry a tab
// and a newline into the value, and the loader would accept it.
//
// A literal string cannot contain a single quote or any control character, so
// those fall back to a basic string with the escapes TOML defines. That path
// is unlikely for a path and entirely possible for a generated namespace key,
// which is why it exists rather than being a refusal.
func tomlString(v string) string {
	if !strings.ContainsRune(v, '\'') && !hasControl(v) {
		return "'" + v + "'"
	}

	var b strings.Builder

	b.WriteByte('"')

	for _, r := range v {
		switch r {
		case '"':
			b.WriteString(`\"`)
		case '\\':
			b.WriteString(`\\`)
		case '\b':
			b.WriteString(`\b`)
		case '\t':
			b.WriteString(`\t`)
		case '\n':
			b.WriteString(`\n`)
		case '\f':
			b.WriteString(`\f`)
		case '\r':
			b.WriteString(`\r`)
		default:
			if isControl(r) {
				fmt.Fprintf(&b, `\u%04X`, r)

				continue
			}

			b.WriteRune(r)
		}
	}

	b.WriteByte('"')

	return b.String()
}

// hasControl reports whether v holds a character a literal string cannot carry.
func hasControl(v string) bool {
	return strings.ContainsFunc(v, isControl)
}

// isControl reports whether r must be escaped in a TOML basic string. Tab is
// included: a literal string may hold one, but a value carrying a tab is far
// more likely to be a paste accident than an intention, and escaping it makes
// it visible in the file.
func isControl(r rune) bool {
	return r == 0x7F || (r < 0x20) || unicode.IsControl(r)
}

// ResolveBytes resolves a config document that has not been written to disk.
//
// It exists so a provisioning run can validate the file it is ABOUT to write.
// Rendering, writing, and then validating leaves a failed run with a config on
// disk carrying a freshly generated identity.namespaceKey that nobody asked
// for — and on the next run that key is indistinguishable from a provisioned
// one, so the mistake is not recoverable by re-running. Writing the projection
// to a temp file to validate it would be the same leak in a worse place.
//
// The environment is excluded, exactly as LoadWithoutEnvironment excludes it:
// the answer this produces must be the one a SERVICE would resolve, and the
// process asking is an elevated operator's shell.
//
// path is recorded as the resolution's config path so the result reports where
// the document is destined for; the file need not exist.
func ResolveBytes(spec Spec, path string, document []byte) (*Values, error) {
	index, err := spec.index()
	if err != nil {
		return nil, err
	}

	var parsed map[string]any

	// Parsed with the same TOML library the loader's file provider uses, then
	// handed to koanf as a map — rather than adding a raw-bytes provider for
	// one caller. Nine direct dependencies is a number this repo watches.
	if err := toml.Unmarshal(document, &parsed); err != nil {
		return nil, fmt.Errorf("parsing the rendered configuration: %w", err)
	}

	k := koanf.New(".")

	if err := k.Load(confmap.Provider(defaults(spec), "."), nil); err != nil {
		return nil, fmt.Errorf("loading defaults: %w", err)
	}

	if err := k.Load(confmap.Provider(parsed, "."), nil); err != nil {
		return nil, fmt.Errorf("loading the rendered configuration: %w", err)
	}

	values, err := resolve(spec, index, k)
	if err != nil {
		return nil, err
	}

	values.configPath = path

	return values, nil
}

// ValueOf returns a registered key's resolved value in the Go type its Type
// implies, without the panic the typed getters raise.
//
// The getters panic because reading the wrong type is a wiring mistake in a
// binary that knows its own keys. A caller comparing a PROVISIONED value
// against a resolved one does not know the type ahead of time — it is holding
// whatever the operator supplied — so it needs an accessor that reports rather
// than crashes.
func ValueOf(v *Values, name string) (any, error) {
	if _, registered := v.spec[name]; !registered {
		return nil, fmt.Errorf("config: key %q is not registered", name)
	}

	return v.values[name], nil
}

// RegisterFlags declares a flag for every settable key in spec on fs, and
// returns a function reporting the keys the caller explicitly set.
//
// It exists so that a provisioning command has no vocabulary of its own. Every
// key already derives exactly one flag name through FlagName, and a command
// that hand-wrote "--server-name" beside a key called identity.serverName
// would be a second spelling nothing reconciles. Reusing the derivation also
// gets NoFlag for free: a key kept out of argv because it is a secret stays
// out of this command's argv too, without that rule being restated.
//
// Only VISITED flags are reported. An unset flag's zero value must never
// become a provisioned value — writing port = 0 into a generated config
// because nobody passed --port is the failure this guards.
//
// The returned function must be called after fs.Parse.
func RegisterFlags(fs *flag.FlagSet, spec Spec) (func() []Provisioned, error) {
	keyOf := make(map[string]string, len(spec))
	valueOf := make(map[string]any, len(spec))
	order := make(map[string]int, len(spec))

	for i, k := range spec {
		// A NoFlag key registers nothing, so its value never lands in argv
		// where any local user could read it out of a process listing.
		if k.NoFlag {
			continue
		}

		name := FlagName(k.Name)
		keyOf[name] = k.Name
		order[k.Name] = i

		switch k.Type {
		case TypeString:
			valueOf[name] = fs.String(name, "", k.Usage)
		case TypeInt:
			valueOf[name] = fs.Int(name, 0, k.Usage)
		case TypeBool:
			valueOf[name] = fs.Bool(name, false, k.Usage)
		case TypeDuration:
			valueOf[name] = fs.Duration(name, 0, k.Usage)
		default:
			return nil, fmt.Errorf("config key %q has an unknown type %d", k.Name, k.Type)
		}
	}

	return func() []Provisioned {
		var out []Provisioned

		fs.Visit(func(f *flag.Flag) {
			key, ok := keyOf[f.Name]
			if !ok {
				return // A flag of the command's own, not a registered key.
			}

			switch p := valueOf[f.Name].(type) {
			case *string:
				out = append(out, Provisioned{Key: key, Value: *p})
			case *int:
				out = append(out, Provisioned{Key: key, Value: *p})
			case *bool:
				out = append(out, Provisioned{Key: key, Value: *p})
			case *time.Duration:
				out = append(out, Provisioned{Key: key, Value: *p})
			}
		})

		// Spec order, not the order they were typed, so a generated file reads
		// the same however the command line was written.
		slices.SortStableFunc(out, func(a, b Provisioned) int {
			return order[a.Key] - order[b.Key]
		})

		return out
	}, nil
}
